// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheBha.Infrastructure.Persistence;

#nullable disable

namespace TheBha.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TheBhaDbContext))]
    [Migration("20260722121010_AddDailyInventoryControls")]
    partial class AddDailyInventoryControls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheBha.Domain.Properties.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Amenities", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyInventoryControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStopSell")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SellableLimit")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "StayDate");

                    b.HasIndex("PropertyId", "RoomTypeId", "StayDate")
                        .IsUnique();

                    b.ToTable("DailyInventoryControls", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyInventoryControls_Effect", "\"SellableLimit\" IS NOT NULL OR \"IsStopSell\" = TRUE");

                            t.HasCheckConstraint("CK_DailyInventoryControls_SellableLimit", "\"SellableLimit\" IS NULL OR \"SellableLimit\" >= 0");

                            t.HasCheckConstraint("CK_DailyInventoryControls_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyRoomRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "StayDate");

                    b.HasIndex("PropertyId", "RatePlanId", "StayDate");

                    b.HasIndex("PropertyId", "RoomTypeId", "StayDate");

                    b.HasIndex("PropertyId", "RoomTypeId", "RatePlanId", "StayDate")
                        .IsUnique();

                    b.ToTable("DailyRoomRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyRoomRates_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_DailyRoomRates_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PhysicalRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "RoomNumber")
                        .IsUnique();

                    b.HasIndex("PropertyId", "RoomTypeId");

                    b.ToTable("PhysicalRooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhysicalRooms_OperationalStatus", "\"OperationalStatus\" IN ('Active', 'Inactive', 'OutOfService')");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeOnly>("CheckInTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("CheckOutTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyAmenity", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyMedia", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("PropertyId", "MediaId");

                    b.HasIndex("MediaId");

                    b.HasIndex("PropertyId")
                        .IsUnique()
                        .HasFilter("\"IsCover\"");

                    b.ToTable("PropertyMedia", null, t =>
                        {
                            t.HasCheckConstraint("CK_PropertyMedia_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RatePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique();

                    b.ToTable("RatePlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_RatePlans_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_RatePlans_CurrencyCode", "\"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_RatePlans_Name_NotBlank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_RatePlans_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique();

                    b.HasIndex("PropertyId", "Slug")
                        .IsUnique();

                    b.ToTable("RoomTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomTypes_BaseOccupancy", "\"BaseOccupancy\" > 0");

                            t.HasCheckConstraint("CK_RoomTypes_MaxOccupancy", "\"MaxOccupancy\" >= \"BaseOccupancy\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeAmenity", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("RoomTypeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomTypeAmenities", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeMedia", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RoomTypeId", "MediaId");

                    b.HasIndex("MediaId");

                    b.HasIndex("RoomTypeId")
                        .IsUnique()
                        .HasFilter("\"IsCover\"");

                    b.ToTable("RoomTypeMedia", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomTypeMedia_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyInventoryControl", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyRoomRate", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RatePlan", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RatePlanId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PhysicalRoom", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyAmenity", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyMedia", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RatePlan", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomType", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeAmenity", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeMedia", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("RoomType");
                });
#pragma warning restore 612, 618
        }
    }
}
