// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheBha.Infrastructure.Persistence;

#nullable disable

namespace TheBha.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TheBhaDbContext))]
    [Migration("20260723105404_AddBookingHoldReservationFoundation")]
    partial class AddBookingHoldReservationFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.BookingHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Adults")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<int>("Children")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GuestAccessTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("IdempotencyKeyHash")
                        .IsUnique();

                    b.HasIndex("PropertyId", "RatePlanId");

                    b.HasIndex("PropertyId", "RoomTypeId", "Status", "ExpiresAtUtc");

                    b.ToTable("BookingHolds", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingHolds_Contact", "btrim(\"FullName\") <> '' AND btrim(\"Email\") <> '' AND btrim(\"Phone\") <> ''");

                            t.HasCheckConstraint("CK_BookingHolds_Currency", "\"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_BookingHolds_FixedLifetime", "\"ExpiresAtUtc\" = \"CreatedAtUtc\" + INTERVAL '15 minutes'");

                            t.HasCheckConstraint("CK_BookingHolds_Hashes", "\"IdempotencyKeyHash\" ~ '^[0-9a-f]{64}$' AND \"RequestFingerprint\" ~ '^[0-9a-f]{64}$' AND (\"GuestAccessTokenHash\" IS NULL OR \"GuestAccessTokenHash\" ~ '^[0-9a-f]{64}$')");

                            t.HasCheckConstraint("CK_BookingHolds_Ids", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"PropertyId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"RoomTypeId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"RatePlanId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND (\"CustomerAccountId\" IS NULL OR \"CustomerAccountId\" <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("CK_BookingHolds_Occupancy", "\"Adults\" >= 1 AND \"Children\" >= 0 AND \"Rooms\" >= 1");

                            t.HasCheckConstraint("CK_BookingHolds_Ownership", "(\"CustomerAccountId\" IS NOT NULL AND \"GuestAccessTokenHash\" IS NULL) OR (\"CustomerAccountId\" IS NULL AND \"GuestAccessTokenHash\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_BookingHolds_Status", "\"Status\" IN ('Active', 'Confirmed', 'Cancelled')");

                            t.HasCheckConstraint("CK_BookingHolds_Stay", "\"CheckIn\" < \"CheckOut\"");

                            t.HasCheckConstraint("CK_BookingHolds_TotalAmount", "\"TotalAmount\" > 0");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.BookingHoldNight", b =>
                {
                    b.Property<Guid>("BookingHoldId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NightTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BookingHoldId", "StayDate");

                    b.HasIndex("StayDate", "BookingHoldId");

                    b.ToTable("BookingHoldNights", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingHoldNights_Amounts", "\"UnitAmount\" > 0 AND \"NightTotal\" > 0 AND \"NightTotal\" = \"UnitAmount\" * \"Rooms\"");

                            t.HasCheckConstraint("CK_BookingHoldNights_BookingHoldId", "\"BookingHoldId\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BookingHoldNights_Rooms", "\"Rooms\" >= 1");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Adults")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<int>("Children")
                        .HasColumnType("integer");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GuestAccessTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceHoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber")
                        .IsUnique();

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("SourceHoldId")
                        .IsUnique();

                    b.HasIndex("PropertyId", "RatePlanId");

                    b.HasIndex("PropertyId", "RoomTypeId", "Status");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_Cancellation", "(\"Status\" = 'Confirmed' AND \"CancelledAtUtc\" IS NULL AND \"CancellationReason\" IS NULL) OR (\"Status\" = 'Cancelled' AND \"CancelledAtUtc\" IS NOT NULL AND \"CancelledAtUtc\" >= \"ConfirmedAtUtc\" AND \"CancellationReason\" IS NOT NULL AND btrim(\"CancellationReason\") <> '')");

                            t.HasCheckConstraint("CK_Reservations_ConfirmationNumber", "\"ConfirmationNumber\" ~ '^[A-Z0-9-]+$'");

                            t.HasCheckConstraint("CK_Reservations_Contact", "btrim(\"FullName\") <> '' AND btrim(\"Email\") <> '' AND btrim(\"Phone\") <> ''");

                            t.HasCheckConstraint("CK_Reservations_Currency", "\"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_Reservations_Hash", "\"GuestAccessTokenHash\" IS NULL OR \"GuestAccessTokenHash\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_Reservations_Ids", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"SourceHoldId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"PropertyId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"RoomTypeId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"RatePlanId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND (\"CustomerAccountId\" IS NULL OR \"CustomerAccountId\" <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("CK_Reservations_Occupancy", "\"Adults\" >= 1 AND \"Children\" >= 0 AND \"Rooms\" >= 1");

                            t.HasCheckConstraint("CK_Reservations_Ownership", "(\"CustomerAccountId\" IS NOT NULL AND \"GuestAccessTokenHash\" IS NULL) OR (\"CustomerAccountId\" IS NULL AND \"GuestAccessTokenHash\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Reservations_Status", "\"Status\" IN ('Confirmed', 'Cancelled')");

                            t.HasCheckConstraint("CK_Reservations_Stay", "\"CheckIn\" < \"CheckOut\"");

                            t.HasCheckConstraint("CK_Reservations_TotalAmount", "\"TotalAmount\" > 0");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.ReservationNight", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NightTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ReservationId", "StayDate");

                    b.HasIndex("StayDate", "ReservationId");

                    b.ToTable("ReservationNights", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReservationNights_Amounts", "\"UnitAmount\" > 0 AND \"NightTotal\" > 0 AND \"NightTotal\" = \"UnitAmount\" * \"Rooms\"");

                            t.HasCheckConstraint("CK_ReservationNights_ReservationId", "\"ReservationId\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ReservationNights_Rooms", "\"Rooms\" >= 1");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Amenities", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyInventoryControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStopSell")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SellableLimit")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "StayDate");

                    b.HasIndex("PropertyId", "RoomTypeId", "StayDate")
                        .IsUnique();

                    b.ToTable("DailyInventoryControls", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyInventoryControls_Effect", "\"SellableLimit\" IS NOT NULL OR \"IsStopSell\" = TRUE");

                            t.HasCheckConstraint("CK_DailyInventoryControls_SellableLimit", "\"SellableLimit\" IS NULL OR \"SellableLimit\" >= 0");

                            t.HasCheckConstraint("CK_DailyInventoryControls_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyRoomRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "StayDate");

                    b.HasIndex("PropertyId", "RatePlanId", "StayDate");

                    b.HasIndex("PropertyId", "RoomTypeId", "StayDate");

                    b.HasIndex("PropertyId", "RoomTypeId", "RatePlanId", "StayDate")
                        .IsUnique();

                    b.ToTable("DailyRoomRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyRoomRates_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_DailyRoomRates_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PhysicalRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "RoomNumber")
                        .IsUnique();

                    b.HasIndex("PropertyId", "RoomTypeId");

                    b.ToTable("PhysicalRooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhysicalRooms_OperationalStatus", "\"OperationalStatus\" IN ('Active', 'Inactive', 'OutOfService')");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeOnly>("CheckInTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("CheckOutTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyAmenity", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyMedia", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("PropertyId", "MediaId");

                    b.HasIndex("MediaId");

                    b.HasIndex("PropertyId")
                        .IsUnique()
                        .HasFilter("\"IsCover\"");

                    b.ToTable("PropertyMedia", null, t =>
                        {
                            t.HasCheckConstraint("CK_PropertyMedia_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RatePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique();

                    b.ToTable("RatePlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_RatePlans_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_RatePlans_CurrencyCode", "\"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_RatePlans_Name_NotBlank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_RatePlans_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique();

                    b.HasIndex("PropertyId", "Slug")
                        .IsUnique();

                    b.ToTable("RoomTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomTypes_BaseOccupancy", "\"BaseOccupancy\" > 0");

                            t.HasCheckConstraint("CK_RoomTypes_MaxOccupancy", "\"MaxOccupancy\" >= \"BaseOccupancy\"");
                        });
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeAmenity", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("RoomTypeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomTypeAmenities", (string)null);
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeMedia", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RoomTypeId", "MediaId");

                    b.HasIndex("MediaId");

                    b.HasIndex("RoomTypeId")
                        .IsUnique()
                        .HasFilter("\"IsCover\"");

                    b.ToTable("RoomTypeMedia", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomTypeMedia_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("TheBha.Infrastructure.Identity.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomerAccounts_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TheBha.Infrastructure.Identity.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TheBha.Infrastructure.Identity.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TheBha.Infrastructure.Identity.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.BookingHold", b =>
                {
                    b.HasOne("TheBha.Infrastructure.Identity.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RatePlan", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RatePlanId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.BookingHoldNight", b =>
                {
                    b.HasOne("TheBha.Domain.Bookings.BookingHold", null)
                        .WithMany("Nights")
                        .HasForeignKey("BookingHoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.Reservation", b =>
                {
                    b.HasOne("TheBha.Infrastructure.Identity.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Bookings.BookingHold", null)
                        .WithOne()
                        .HasForeignKey("TheBha.Domain.Bookings.Reservation", "SourceHoldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RatePlan", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RatePlanId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.ReservationNight", b =>
                {
                    b.HasOne("TheBha.Domain.Bookings.Reservation", null)
                        .WithMany("Nights")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyInventoryControl", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.DailyRoomRate", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RatePlan", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RatePlanId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PhysicalRoom", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", null)
                        .WithMany()
                        .HasForeignKey("PropertyId", "RoomTypeId")
                        .HasPrincipalKey("PropertyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyAmenity", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TheBha.Domain.Properties.PropertyMedia", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RatePlan", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomType", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeAmenity", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("TheBha.Domain.Properties.RoomTypeMedia", b =>
                {
                    b.HasOne("TheBha.Domain.Properties.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBha.Domain.Properties.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.BookingHold", b =>
                {
                    b.Navigation("Nights");
                });

            modelBuilder.Entity("TheBha.Domain.Bookings.Reservation", b =>
                {
                    b.Navigation("Nights");
                });
#pragma warning restore 612, 618
        }
    }
}
