import { MediaDto } from "./propertyTypes";

/**
 * Wire types for GET /api/v1/properties/{propertyId}/availability, matched
 * to the live /swagger/v1/swagger.json document generated by TheBha.Api.
 * Casing/nullability follows the same established Swashbuckle convention
 * already used for PropertyDto/RoomTypeDto: every reference-type property is
 * nullable in the generated schema regardless of the backend record's C#
 * annotations, while GUID/date/numeric fields are required. PhysicalRoom,
 * Hold, Reservation, tax, discount, and currency-conversion fields are
 * intentionally absent; this is a read-only availability snapshot contract.
 */

/** The five query parameters accepted by the Availability endpoint. */
export interface AvailabilityQuery {
  /** ISO hotel date "YYYY-MM-DD". Half-open range start (inclusive). */
  checkIn: string;
  /** ISO hotel date "YYYY-MM-DD". Half-open range end (exclusive). */
  checkOut: string;
  adults: number;
  children: number;
  rooms: number;
}

export interface NightlyRateDto {
  stayDate: string;
  amount: number;
}

export interface AvailabilityOfferDto {
  propertyId: string;
  roomTypeId: string;
  roomTypeCode: string | null;
  roomTypeName: string | null;
  roomTypeDescription: string | null;
  media: MediaDto[] | null;
  ratePlanId: string;
  ratePlanCode: string | null;
  ratePlanName: string | null;
  currencyCode: string | null;
  checkIn: string;
  checkOut: string;
  nights: number;
  requestedRooms: number;
  availableRooms: number;
  nightlyRates: NightlyRateDto[] | null;
  totalAmount: number;
}
