/**
 * Wire types for GET /api/v1/auth/csrf, POST /api/v1/booking-holds, and
 * POST /api/v1/booking-holds/{holdId}/confirm, matched to the live
 * /swagger/v1/swagger.json document generated by TheBha.Api
 * (CsrfTokenResponse, CreateBookingHoldApiRequest, BookingHoldDto,
 * BookingHoldNightDto, BookingHoldStatus, ReservationDto,
 * ReservationNightDto, ReservationStatus). Casing/nullability follows the
 * same established Swashbuckle convention already used for
 * PropertyDto/AvailabilityOfferDto: reference-type fields are nullable in
 * the generated schema; GUID/date/numeric fields are required.
 * Cancellation, payment, and internal/ownership fields are intentionally
 * absent beyond the Reservation fields the confirm response already
 * carries.
 */

/** Serialized BookingHoldStatus values (JsonStringEnumConverter). */
export type BookingHoldStatus = "Active" | "Confirmed" | "Cancelled";

export interface CsrfTokenResponse {
  token: string | null;
  headerName: string | null;
}

/** Only the fields the backend accepts as authoritative client input. */
export interface CreateBookingHoldRequest {
  propertyId: string;
  roomTypeId: string;
  ratePlanId: string;
  checkIn: string;
  checkOut: string;
  adults: number;
  children: number;
  rooms: number;
  fullName: string;
  email: string;
  phone: string;
}

export interface BookingHoldNightDto {
  stayDate: string;
  rooms: number;
  unitAmount: number;
  nightTotal: number;
}

export interface BookingHoldDto {
  holdId: string;
  status: BookingHoldStatus;
  propertyId: string;
  roomTypeId: string;
  ratePlanId: string;
  checkIn: string;
  checkOut: string;
  adults: number;
  children: number;
  rooms: number;
  currencyCode: string | null;
  totalAmount: number;
  createdAtUtc: string;
  expiresAtUtc: string;
  nights: BookingHoldNightDto[] | null;
  guestAccessToken: string | null;
}

/** Serialized ReservationStatus values (JsonStringEnumConverter). */
export type ReservationStatus = "Confirmed" | "Cancelled";

export interface ReservationNightDto {
  stayDate: string;
  rooms: number;
  unitAmount: number;
  nightTotal: number;
}

export interface ReservationDto {
  reservationId: string;
  confirmationNumber: string | null;
  status: ReservationStatus;
  propertyId: string;
  roomTypeId: string;
  ratePlanId: string;
  fullName: string | null;
  email: string | null;
  phone: string | null;
  checkIn: string;
  checkOut: string;
  adults: number;
  children: number;
  rooms: number;
  currencyCode: string | null;
  totalAmount: number;
  confirmedAtUtc: string;
  cancelledAtUtc: string | null;
  cancellationReason: string | null;
  nights: ReservationNightDto[] | null;
}
