// Wire types for GET /api/v1/properties and
// GET /api/v1/properties/{propertyId}/room-types, matched to the live
// /swagger/v1/swagger.json document generated by TheBha.Api.
// PhysicalRoom, RatePlan, Availability and booking contracts are
// intentionally out of scope for FE-001.2.

export type MediaType = "Image" | "Video";

export interface AmenityDto {
  id: string;
  code: string | null;
  name: string | null;
  category: string | null;
}

export interface MediaDto {
  id: string;
  url: string | null;
  altText: string | null;
  mediaType: MediaType;
  sortOrder: number;
  isCover: boolean;
}

export interface PropertyDto {
  id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  timeZone: string | null;
  /** Server-provided TimeOnly, e.g. "14:00:00". */
  checkInTime: string;
  /** Server-provided TimeOnly, e.g. "12:00:00". */
  checkOutTime: string;
  amenities: AmenityDto[] | null;
  media: MediaDto[] | null;
}

/**
 * RoomTypeDto casing/nullability matches the generated OpenAPI schema, which
 * (like PropertyDto above) marks every reference-type property nullable
 * regardless of the backend record's C# nullable annotations — a known
 * Swashbuckle/records quirk already resolved this way for PropertyDto in
 * FE-001.1. PhysicalRoom, RatePlan, pricing, and availability fields are
 * intentionally absent; this is a read-only catalog contract.
 */
export interface RoomTypeDto {
  id: string;
  propertyId: string;
  code: string | null;
  name: string | null;
  slug: string | null;
  description: string | null;
  baseOccupancy: number;
  maxOccupancy: number;
  amenities: AmenityDto[] | null;
  media: MediaDto[] | null;
}
