// Wire types for GET /api/v1/properties, matched to the live
// /swagger/v1/swagger.json document generated by TheBha.Api.
// PhysicalRoom, RoomType, RatePlan, Availability and booking contracts are
// intentionally out of scope for FE-001.1.

export type MediaType = "Image" | "Video";

export interface AmenityDto {
  id: string;
  code: string | null;
  name: string | null;
  category: string | null;
}

export interface MediaDto {
  id: string;
  url: string | null;
  altText: string | null;
  mediaType: MediaType;
  sortOrder: number;
  isCover: boolean;
}

export interface PropertyDto {
  id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  timeZone: string | null;
  /** Server-provided TimeOnly, e.g. "14:00:00". */
  checkInTime: string;
  /** Server-provided TimeOnly, e.g. "12:00:00". */
  checkOutTime: string;
  amenities: AmenityDto[] | null;
  media: MediaDto[] | null;
}
